/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import business.DespesaInvalidaException;
import business.EmailInvalidoException;
import business.Facade;
import business.PagamentoInvalidoException;
import business.PercentagemInvalidaException;
import business.ValorInvalidoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Fábio Baião
 */
public class MainWindow extends javax.swing.JFrame {

    private Facade f;
    private List<String> despesas;
    private List<String> despesasIndividuais;
    private List<String> pagamentos;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    MainWindow(Facade f) {
        initComponents();
        this.f = f;
        this.apresentarDespesas();
        this.apresentarDespesasIndividuais();
        this.apresentarPagamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adicionarDespesaJanela = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        descricaoAdicionarDespesa = new javax.swing.JTextField();
        diaAdicionarDespesa = new javax.swing.JComboBox<>();
        mesAdicionarDespesa = new javax.swing.JComboBox<>();
        anoAdicionarDespesa = new javax.swing.JComboBox<>();
        valorAdicionarDespesa = new javax.swing.JTextField();
        recorrenteAdicionarDespesa = new javax.swing.JRadioButton();
        extraordinariaAdicionarDespesa = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        equitativaAdicionarDespesa = new javax.swing.JRadioButton();
        percentualAdicionarDespesa = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        moradoresAdicionarDespesa = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        percentagensAdicionarDespesa = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        cancelarAdicionarDespesa = new javax.swing.JButton();
        okAdicionarDespesa = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        dialogoExcecao = new javax.swing.JDialog();
        mensagemExcecao = new javax.swing.JTextField();
        okExcecao = new javax.swing.JButton();
        editarDespesaJanela = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        descricaoEditarDespesa = new javax.swing.JTextField();
        valorEditarDespesa = new javax.swing.JTextField();
        diaEditarDespesa = new javax.swing.JComboBox<>();
        mesEditarDespesa = new javax.swing.JComboBox<>();
        anoEditarDespesa = new javax.swing.JComboBox<>();
        cancelarEditarDespesa = new javax.swing.JButton();
        okEditarDespesa = new javax.swing.JButton();
        eliminarDespesaDialogo = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        naoEliminarDespesa = new javax.swing.JButton();
        simEliminarDespesa = new javax.swing.JButton();
        efetuarPagamentoJanela = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        valorEfetuarPagamento = new javax.swing.JTextField();
        numerarioEfetuarPagamento = new javax.swing.JRadioButton();
        transferenciaEfetuarPagamento = new javax.swing.JRadioButton();
        cancelarEfetuarPagamento = new javax.swing.JButton();
        okEfetuarPagamento = new javax.swing.JButton();
        diaEfetuarPagamento = new javax.swing.JComboBox<>();
        mesEfetuarPagamento = new javax.swing.JComboBox<>();
        anoEfetuarPagamento = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        buttonGroup3 = new javax.swing.ButtonGroup();
        eliminarPagamentoDialogo = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        naoEliminarPagamento = new javax.swing.JButton();
        simEliminarPagamento = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDespesas = new javax.swing.JList<>();
        adicionarDespesa = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        editarDespesa = new javax.swing.JButton();
        eliminarDespesa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaDespesasIndividuais = new javax.swing.JList<>();
        efetuarPagamento = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaPagamentos = new javax.swing.JList<>();
        eliminarPagamento = new javax.swing.JButton();

        adicionarDespesaJanela.setMinimumSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Adicionar Despesa");

        jLabel2.setText("Descricao");

        jLabel3.setText("Data Limite");

        jLabel4.setText("Valor");

        jLabel5.setText("Tipo");

        diaAdicionarDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesAdicionarDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        anoAdicionarDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018" }));

        buttonGroup1.add(recorrenteAdicionarDespesa);
        recorrenteAdicionarDespesa.setText("Recorrente");

        buttonGroup1.add(extraordinariaAdicionarDespesa);
        extraordinariaAdicionarDespesa.setText("Extraordinaria");

        jLabel6.setText("Divisao");

        buttonGroup2.add(equitativaAdicionarDespesa);
        equitativaAdicionarDespesa.setText("Equitativa");

        buttonGroup2.add(percentualAdicionarDespesa);
        percentualAdicionarDespesa.setText("Percentual");

        jLabel7.setText("Moradores");

        moradoresAdicionarDespesa.setColumns(20);
        moradoresAdicionarDespesa.setRows(5);
        jScrollPane2.setViewportView(moradoresAdicionarDespesa);

        percentagensAdicionarDespesa.setColumns(20);
        percentagensAdicionarDespesa.setRows(5);
        jScrollPane3.setViewportView(percentagensAdicionarDespesa);

        jLabel8.setText("Percentagens");

        cancelarAdicionarDespesa.setText("Cancelar");
        cancelarAdicionarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarAdicionarDespesaActionPerformed(evt);
            }
        });

        okAdicionarDespesa.setText("OK");
        okAdicionarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAdicionarDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adicionarDespesaJanelaLayout = new javax.swing.GroupLayout(adicionarDespesaJanela.getContentPane());
        adicionarDespesaJanela.getContentPane().setLayout(adicionarDespesaJanelaLayout);
        adicionarDespesaJanelaLayout.setHorizontalGroup(
            adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                        .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                                        .addComponent(diaAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anoAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(valorAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                                        .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descricaoAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                                                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(recorrenteAdicionarDespesa)
                                                    .addComponent(equitativaAdicionarDespesa))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(percentualAdicionarDespesa)
                                                    .addComponent(extraordinariaAdicionarDespesa))))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adicionarDespesaJanelaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(92, 92, 92))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adicionarDespesaJanelaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okAdicionarDespesa)
                        .addGap(18, 18, 18)
                        .addComponent(cancelarAdicionarDespesa)))
                .addContainerGap())
        );
        adicionarDespesaJanelaLayout.setVerticalGroup(
            adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descricaoAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(diaAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(valorAdicionarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(recorrenteAdicionarDespesa)
                    .addComponent(extraordinariaAdicionarDespesa))
                .addGap(18, 18, 18)
                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equitativaAdicionarDespesa)
                    .addComponent(percentualAdicionarDespesa)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(adicionarDespesaJanelaLayout.createSequentialGroup()
                        .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(adicionarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarAdicionarDespesa)
                    .addComponent(okAdicionarDespesa))
                .addContainerGap())
        );

        dialogoExcecao.setMinimumSize(new java.awt.Dimension(400, 144));

        mensagemExcecao.setEditable(false);

        okExcecao.setText("OK");
        okExcecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okExcecaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoExcecaoLayout = new javax.swing.GroupLayout(dialogoExcecao.getContentPane());
        dialogoExcecao.getContentPane().setLayout(dialogoExcecaoLayout);
        dialogoExcecaoLayout.setHorizontalGroup(
            dialogoExcecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoExcecaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensagemExcecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoExcecaoLayout.createSequentialGroup()
                .addContainerGap(334, Short.MAX_VALUE)
                .addComponent(okExcecao)
                .addGap(19, 19, 19))
        );
        dialogoExcecaoLayout.setVerticalGroup(
            dialogoExcecaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoExcecaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mensagemExcecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okExcecao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        editarDespesaJanela.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Editar Despesa");

        jLabel11.setText("Descricao");

        jLabel12.setText("Data Limite");

        jLabel13.setText("Valor");

        diaEditarDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesEditarDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        anoEditarDespesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018" }));

        cancelarEditarDespesa.setText("Cancelar");
        cancelarEditarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEditarDespesaActionPerformed(evt);
            }
        });

        okEditarDespesa.setText("OK");
        okEditarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okEditarDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editarDespesaJanelaLayout = new javax.swing.GroupLayout(editarDespesaJanela.getContentPane());
        editarDespesaJanela.getContentPane().setLayout(editarDespesaJanelaLayout);
        editarDespesaJanelaLayout.setHorizontalGroup(
            editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarDespesaJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(editarDespesaJanelaLayout.createSequentialGroup()
                        .addGroup(editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(editarDespesaJanelaLayout.createSequentialGroup()
                                .addComponent(diaEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anoEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descricaoEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarDespesaJanelaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(okEditarDespesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarEditarDespesa)
                .addContainerGap())
        );
        editarDespesaJanelaLayout.setVerticalGroup(
            editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarDespesaJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(descricaoEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(diaEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(valorEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(editarDespesaJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarEditarDespesa)
                    .addComponent(okEditarDespesa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        eliminarDespesaDialogo.setMinimumSize(new java.awt.Dimension(400, 150));

        jLabel14.setText("Tem a certeza que pretende eliminar a despesa selecionada? ");

        naoEliminarDespesa.setText("Nao");
        naoEliminarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoEliminarDespesaActionPerformed(evt);
            }
        });

        simEliminarDespesa.setText("Sim");
        simEliminarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simEliminarDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarDespesaDialogoLayout = new javax.swing.GroupLayout(eliminarDespesaDialogo.getContentPane());
        eliminarDespesaDialogo.getContentPane().setLayout(eliminarDespesaDialogoLayout);
        eliminarDespesaDialogoLayout.setHorizontalGroup(
            eliminarDespesaDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarDespesaDialogoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eliminarDespesaDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(eliminarDespesaDialogoLayout.createSequentialGroup()
                        .addComponent(simEliminarDespesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(naoEliminarDespesa))
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        eliminarDespesaDialogoLayout.setVerticalGroup(
            eliminarDespesaDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarDespesaDialogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(eliminarDespesaDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naoEliminarDespesa)
                    .addComponent(simEliminarDespesa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        efetuarPagamentoJanela.setMinimumSize(new java.awt.Dimension(400, 300));

        jLabel16.setText("Efetuar Pagamento");

        jLabel17.setText("Valor");

        jLabel18.setText("Metodo");

        buttonGroup3.add(numerarioEfetuarPagamento);
        numerarioEfetuarPagamento.setText("Numerario");

        buttonGroup3.add(transferenciaEfetuarPagamento);
        transferenciaEfetuarPagamento.setText("Transferencia");

        cancelarEfetuarPagamento.setText("Cancelar");
        cancelarEfetuarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarEfetuarPagamentoActionPerformed(evt);
            }
        });

        okEfetuarPagamento.setText("OK");
        okEfetuarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okEfetuarPagamentoActionPerformed(evt);
            }
        });

        diaEfetuarPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesEfetuarPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Marco", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));

        anoEfetuarPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2016", "2017", "2018" }));

        jLabel19.setText("Data");

        javax.swing.GroupLayout efetuarPagamentoJanelaLayout = new javax.swing.GroupLayout(efetuarPagamentoJanela.getContentPane());
        efetuarPagamentoJanela.getContentPane().setLayout(efetuarPagamentoJanelaLayout);
        efetuarPagamentoJanelaLayout.setHorizontalGroup(
            efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(efetuarPagamentoJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(efetuarPagamentoJanelaLayout.createSequentialGroup()
                        .addGroup(efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(efetuarPagamentoJanelaLayout.createSequentialGroup()
                                .addGroup(efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valorEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numerarioEfetuarPagamento)
                                    .addComponent(transferenciaEfetuarPagamento)
                                    .addGroup(efetuarPagamentoJanelaLayout.createSequentialGroup()
                                        .addComponent(diaEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mesEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(anoEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(164, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, efetuarPagamentoJanelaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okEfetuarPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarEfetuarPagamento)
                        .addGap(8, 8, 8))))
        );
        efetuarPagamentoJanelaLayout.setVerticalGroup(
            efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(efetuarPagamentoJanelaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(valorEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(numerarioEfetuarPagamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferenciaEfetuarPagamento)
                .addGap(18, 18, 18)
                .addGroup(efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoEfetuarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(efetuarPagamentoJanelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okEfetuarPagamento)
                    .addComponent(cancelarEfetuarPagamento))
                .addContainerGap())
        );

        eliminarPagamentoDialogo.setMinimumSize(new java.awt.Dimension(400, 120));

        jLabel21.setText("Tem a certeza que pretende eliminar o pagamento selecionado?");

        naoEliminarPagamento.setText("Nao");
        naoEliminarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naoEliminarPagamentoActionPerformed(evt);
            }
        });

        simEliminarPagamento.setText("Sim");
        simEliminarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simEliminarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eliminarPagamentoDialogoLayout = new javax.swing.GroupLayout(eliminarPagamentoDialogo.getContentPane());
        eliminarPagamentoDialogo.getContentPane().setLayout(eliminarPagamentoDialogoLayout);
        eliminarPagamentoDialogoLayout.setHorizontalGroup(
            eliminarPagamentoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarPagamentoDialogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eliminarPagamentoDialogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(simEliminarPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(naoEliminarPagamento)
                .addContainerGap())
        );
        eliminarPagamentoDialogoLayout.setVerticalGroup(
            eliminarPagamentoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eliminarPagamentoDialogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(eliminarPagamentoDialogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naoEliminarPagamento)
                    .addComponent(simEliminarPagamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaDespesas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaDespesas);

        adicionarDespesa.setText("Adicionar");
        adicionarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarDespesaActionPerformed(evt);
            }
        });

        jLabel9.setText("ID - Descricao - Data Limite - Tipo - Valor a Pagar - Valor Pago");

        editarDespesa.setText("Editar");
        editarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarDespesaActionPerformed(evt);
            }
        });

        eliminarDespesa.setText("Eliminar");
        eliminarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDespesaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adicionarDespesa)
                .addGap(18, 18, 18)
                .addComponent(editarDespesa)
                .addGap(18, 18, 18)
                .addComponent(eliminarDespesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarDespesa)
                    .addComponent(editarDespesa)
                    .addComponent(eliminarDespesa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Despesas", jPanel1);

        jLabel15.setText("ID - Descricao - Criador - Data Limite - Tipo - Valor - ValorPago");

        listaDespesasIndividuais.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listaDespesasIndividuais);

        efetuarPagamento.setText("Efetuar Pagamento");
        efetuarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efetuarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(0, 78, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(efetuarPagamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(efetuarPagamento)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Despesas Individuais", jPanel2);

        jLabel20.setText("IDDespesa - IDPagameto - Descricao - Data - Valor - ");

        listaPagamentos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listaPagamentos);

        eliminarPagamento.setText("Eliminar");
        eliminarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarPagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(0, 121, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eliminarPagamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarPagamento)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pagamentos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarDespesaActionPerformed
        // TODO add your handling code here:
        this.adicionarDespesaJanela.setVisible(true);
    }//GEN-LAST:event_adicionarDespesaActionPerformed

    private void cancelarAdicionarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarAdicionarDespesaActionPerformed
        // TODO add your handling code here:
        this.adicionarDespesaJanela.dispose();
    }//GEN-LAST:event_cancelarAdicionarDespesaActionPerformed

    private void okAdicionarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAdicionarDespesaActionPerformed
        // TODO add your handling code here:
        String descricao = this.descricaoAdicionarDespesa.getText();
        if (descricao.equals("")){
            this.mensagemExcecao.setText("Descricao invalida!");
            this.dialogoExcecao.setVisible(true);
            return;
        }
        String dataLimite = this.diaAdicionarDespesa.getSelectedItem() + "-" + this.mesAdicionarDespesa.getSelectedItem() + "-" + this.anoAdicionarDespesa.getSelectedItem();
        double valor = 0;
        try{
            valor = Double.parseDouble(this.valorAdicionarDespesa.getText());
        }
        catch(NumberFormatException e){
            this.mensagemExcecao.setText("Valor invalido!");
            this.dialogoExcecao.setVisible(true);
            return;
        }
        String tipo = "";
        if (this.recorrenteAdicionarDespesa.isSelected()){
            tipo = "Recorrente";
        }
        if (this.extraordinariaAdicionarDespesa.isSelected()){
            tipo = "Extraordinaria";
        }
        if (tipo.equals("")){
            this.mensagemExcecao.setText("Tem de selecionar um tipo!");
            this.dialogoExcecao.setVisible(true);
            return;
        }
        try{
            if (this.equitativaAdicionarDespesa.isSelected()){
                String m = this.moradoresAdicionarDespesa.getText();
                List<String> moradores = new ArrayList<>();
                String[] strs = m.split("\n");
                for (String s : strs){
                    s = s.trim();
                    if (!s.equals(""))
                        moradores.add(s);
                }
                f.adicionarDespesa(descricao, valor, moradores, tipo, dataLimite);
                this.adicionarDespesaJanela.dispose();
                apresentarDespesas();
            }
            else if (this.percentualAdicionarDespesa.isSelected()){
                String m = this.moradoresAdicionarDespesa.getText();
                List<String> moradores = new ArrayList<>();
                String[] strs = m.split("\n");
                for (String s : strs){
                    s = s.trim();
                    if (!s.equals(""))
                        moradores.add(s);
                }
                m = this.percentagensAdicionarDespesa.getText();
                List<Double> percentagens = new ArrayList<>();
                strs = m.split("\n");
                for (String s : strs){
                    s = s.trim();
                    if (!s.equals(""))
                        percentagens.add(Double.parseDouble(s));
                }
                f.adicionarDespesa(descricao, valor, moradores, percentagens, tipo, dataLimite);
                this.adicionarDespesaJanela.dispose();
                apresentarDespesas();
            }
            else{
                this.mensagemExcecao.setText("Tem de selecionar divisao!");
                this.dialogoExcecao.setVisible(true);
            }
        }
        catch (EmailInvalidoException | ValorInvalidoException | PercentagemInvalidaException | DespesaInvalidaException e){
            this.mensagemExcecao.setText(e.getMessage());
            this.dialogoExcecao.setVisible(true);
        }
        
    }//GEN-LAST:event_okAdicionarDespesaActionPerformed

    private void okExcecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okExcecaoActionPerformed
        // TODO add your handling code here:
        this.dialogoExcecao.dispose();
    }//GEN-LAST:event_okExcecaoActionPerformed

    private void editarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarDespesaActionPerformed
        // TODO add your handling code here:
        int i = this.listaDespesas.getSelectedIndex();
        if (i == -1){
            this.mensagemExcecao.setText("Tem de selecionar uma despesa");
            this.dialogoExcecao.setVisible(true);
            return;
        }
        this.editarDespesaJanela.setVisible(true);
    }//GEN-LAST:event_editarDespesaActionPerformed

    private void okEditarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okEditarDespesaActionPerformed
        // TODO add your handling code here:
        int i = this.listaDespesas.getSelectedIndex();
        String s = this.despesas.get(i);
        String[] ss = s.split(" ");
        int id = Integer.parseInt(ss[0]);
        try{
            String descricao = this.descricaoEditarDespesa.getText();
            if (!descricao.equals("")){
                f.editarDescricao(id, descricao);
            }
            String dataLimite = this.diaEditarDespesa.getSelectedItem() + "-" + this.mesEditarDespesa.getSelectedItem() + "-" + this.anoEditarDespesa.getSelectedItem();
            f.editarData(id, dataLimite);
            s = this.valorEditarDespesa.getText();
            if (!s.equals("")){
                try{
                    double valor = Double.parseDouble(s);
                    f.editarValor(id, valor);
                }
                catch (NumberFormatException e){
                    this.mensagemExcecao.setText("Valor invalido");
                    this.dialogoExcecao.setVisible(true);
                }
            }
            apresentarDespesas();
            this.editarDespesaJanela.dispose();
        }
        catch (DespesaInvalidaException | ValorInvalidoException e){
            this.mensagemExcecao.setText(e.getMessage());
            this.dialogoExcecao.setVisible(true);
        }
    }//GEN-LAST:event_okEditarDespesaActionPerformed

    private void cancelarEditarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEditarDespesaActionPerformed
        // TODO add your handling code here:
        this.editarDespesaJanela.dispose();
    }//GEN-LAST:event_cancelarEditarDespesaActionPerformed

    private void eliminarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDespesaActionPerformed
        // TODO add your handling code here:
        int i = this.listaDespesas.getSelectedIndex();
        if (i == -1){
            this.mensagemExcecao.setText("Tem de selecionar uma despesa");
            this.dialogoExcecao.setVisible(true);
            return;
        }
        this.eliminarDespesaDialogo.setVisible(true);
    }//GEN-LAST:event_eliminarDespesaActionPerformed

    private void naoEliminarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoEliminarDespesaActionPerformed
        // TODO add your handling code here:
        this.eliminarDespesaDialogo.dispose();
        
    }//GEN-LAST:event_naoEliminarDespesaActionPerformed

    private void simEliminarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simEliminarDespesaActionPerformed
        // TODO add your handling code here:
        int i = this.listaDespesas.getSelectedIndex();
        String s = this.despesas.get(i);
        String[] ss = s.split(" ");
        int id = Integer.parseInt(ss[0]);
        try {
            f.eliminarDespesa(id);
            apresentarDespesas();
            apresentarPagamentos();
        } catch (DespesaInvalidaException ex) {
            this.mensagemExcecao.setText(ex.getMessage());
            this.dialogoExcecao.setVisible(true);
        }
        this.eliminarDespesaDialogo.dispose();
    }//GEN-LAST:event_simEliminarDespesaActionPerformed

    private void efetuarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efetuarPagamentoActionPerformed
        // TODO add your handling code here:
        int i = this.listaDespesasIndividuais.getSelectedIndex();
        if (i == -1){
            this.mensagemExcecao.setText("Tem de selecionar uma despesa individual");
            this.dialogoExcecao.setVisible(true);
            return;
        }
        this.efetuarPagamentoJanela.setVisible(true);
    }//GEN-LAST:event_efetuarPagamentoActionPerformed

    private void cancelarEfetuarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarEfetuarPagamentoActionPerformed
        // TODO add your handling code here:
        this.efetuarPagamentoJanela.dispose();
    }//GEN-LAST:event_cancelarEfetuarPagamentoActionPerformed

    private void okEfetuarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okEfetuarPagamentoActionPerformed
        // TODO add your handling code here:
        int i = this.listaDespesasIndividuais.getSelectedIndex();
        String s = this.despesasIndividuais.get(i);
        String[] ss = s.split(" ");
        int id = Integer.parseInt(ss[0]);
        
        s = this.valorEfetuarPagamento.getText();
        double valor;
        try{
            valor = Double.parseDouble(s);
        }
        catch(NumberFormatException e){
            this.mensagemExcecao.setText("Valor invalido!");
            this.dialogoExcecao.setVisible(true);
            return;
        }
        String data = this.diaEfetuarPagamento.getSelectedItem() + "-" + this.mesEfetuarPagamento.getSelectedItem() + "-" + this.anoEfetuarPagamento.getSelectedItem();
        try{
            if (this.numerarioEfetuarPagamento.isSelected()){
                f.efetuarPagamento(id, valor, "Numerario", data);
                apresentarDespesasIndividuais();
                apresentarPagamentos();
                this.efetuarPagamentoJanela.dispose();
                return;
            }
            if (this.transferenciaEfetuarPagamento.isSelected()){
                f.efetuarPagamento(id, valor, "Transferencia", data);
                apresentarDespesasIndividuais();
                apresentarPagamentos();
                this.efetuarPagamentoJanela.dispose();
                return;
            }
            this.mensagemExcecao.setText("Tem de selecionar um metodo!");
            this.dialogoExcecao.setVisible(true);
        }
        catch (ValorInvalidoException | DespesaInvalidaException e){
            this.mensagemExcecao.setText(e.getMessage());
            this.dialogoExcecao.setVisible(true);
        }
    }//GEN-LAST:event_okEfetuarPagamentoActionPerformed

    private void eliminarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarPagamentoActionPerformed
        // TODO add your handling code here:
        int i = this.listaPagamentos.getSelectedIndex();
        if (i == -1){
            this.mensagemExcecao.setText("Tem de selecionar um pagamento");
            this.dialogoExcecao.setVisible(true);
            return;
        }
        this.eliminarPagamentoDialogo.setVisible(true);
    }//GEN-LAST:event_eliminarPagamentoActionPerformed

    private void naoEliminarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naoEliminarPagamentoActionPerformed
        // TODO add your handling code here:
        this.eliminarPagamentoDialogo.dispose();
    }//GEN-LAST:event_naoEliminarPagamentoActionPerformed

    private void simEliminarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simEliminarPagamentoActionPerformed
        // TODO add your handling code here:
        int i = this.listaPagamentos.getSelectedIndex();
        String s = this.pagamentos.get(i);
        String[] ss = s.split(" ");
        int idDespesa = Integer.parseInt(ss[0]);
        int idPagamento = Integer.parseInt(ss[2]);
        try {
            f.eliminarPagamento(idDespesa, idPagamento);
            apresentarDespesasIndividuais();
            apresentarPagamentos();
        } catch (DespesaInvalidaException | PagamentoInvalidoException ex) {
            this.mensagemExcecao.setText(ex.getMessage());
            this.dialogoExcecao.setVisible(true);
        }
        this.eliminarPagamentoDialogo.dispose();
    }//GEN-LAST:event_simEliminarPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarDespesa;
    private javax.swing.JFrame adicionarDespesaJanela;
    private javax.swing.JComboBox<String> anoAdicionarDespesa;
    private javax.swing.JComboBox<String> anoEditarDespesa;
    private javax.swing.JComboBox<String> anoEfetuarPagamento;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton cancelarAdicionarDespesa;
    private javax.swing.JButton cancelarEditarDespesa;
    private javax.swing.JButton cancelarEfetuarPagamento;
    private javax.swing.JTextField descricaoAdicionarDespesa;
    private javax.swing.JTextField descricaoEditarDespesa;
    private javax.swing.JComboBox<String> diaAdicionarDespesa;
    private javax.swing.JComboBox<String> diaEditarDespesa;
    private javax.swing.JComboBox<String> diaEfetuarPagamento;
    private javax.swing.JDialog dialogoExcecao;
    private javax.swing.JButton editarDespesa;
    private javax.swing.JFrame editarDespesaJanela;
    private javax.swing.JButton efetuarPagamento;
    private javax.swing.JFrame efetuarPagamentoJanela;
    private javax.swing.JButton eliminarDespesa;
    private javax.swing.JDialog eliminarDespesaDialogo;
    private javax.swing.JButton eliminarPagamento;
    private javax.swing.JDialog eliminarPagamentoDialogo;
    private javax.swing.JRadioButton equitativaAdicionarDespesa;
    private javax.swing.JRadioButton extraordinariaAdicionarDespesa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listaDespesas;
    private javax.swing.JList<String> listaDespesasIndividuais;
    private javax.swing.JList<String> listaPagamentos;
    private javax.swing.JTextField mensagemExcecao;
    private javax.swing.JComboBox<String> mesAdicionarDespesa;
    private javax.swing.JComboBox<String> mesEditarDespesa;
    private javax.swing.JComboBox<String> mesEfetuarPagamento;
    private javax.swing.JTextArea moradoresAdicionarDespesa;
    private javax.swing.JButton naoEliminarDespesa;
    private javax.swing.JButton naoEliminarPagamento;
    private javax.swing.JRadioButton numerarioEfetuarPagamento;
    private javax.swing.JButton okAdicionarDespesa;
    private javax.swing.JButton okEditarDespesa;
    private javax.swing.JButton okEfetuarPagamento;
    private javax.swing.JButton okExcecao;
    private javax.swing.JTextArea percentagensAdicionarDespesa;
    private javax.swing.JRadioButton percentualAdicionarDespesa;
    private javax.swing.JRadioButton recorrenteAdicionarDespesa;
    private javax.swing.JButton simEliminarDespesa;
    private javax.swing.JButton simEliminarPagamento;
    private javax.swing.JRadioButton transferenciaEfetuarPagamento;
    private javax.swing.JTextField valorAdicionarDespesa;
    private javax.swing.JTextField valorEditarDespesa;
    private javax.swing.JTextField valorEfetuarPagamento;
    // End of variables declaration//GEN-END:variables

    private void apresentarDespesas() {
        this.despesas = f.consultarDespesas();
        DefaultListModel<String> l = new DefaultListModel<>();
        for (String s : despesas){
            l.addElement(s);
        }
        listaDespesas.setModel(l);
    }
    
    private void apresentarDespesasIndividuais() {
        this.despesasIndividuais = f.consultarDespesasIndividuais();
        DefaultListModel<String> l = new DefaultListModel<>();
        for (String s : despesasIndividuais){
            l.addElement(s);
        }
        listaDespesasIndividuais.setModel(l);
    }
    
    private void apresentarPagamentos() {
        this.pagamentos = f.consultarPagamentos();
        DefaultListModel<String> l = new DefaultListModel<>();
        for (String s : pagamentos){
            l.addElement(s);
        }
        listaPagamentos.setModel(l);
    }
}
